use std::num::ParseIntError;

// define a generic alias for a Result with the error type
// ParseIntError
type AliasedResult<T> = Result<T, ParseIntError>;

// use the above alias to refer to our specific Result type
fn multipy(first_number_str: &str, second_number_str: &str) -> AliasedResult<i32> {
    first_number_str.parse::<i32>().and_then(|first_number| {
        second_number_str.parse::<i32>().map(|second_number| first_number * second_number)
    })
}

// the alias again allows us to save some space
fn print(result: AliasedResult<i32>) {
    match result {
        Ok(n)  => println!("n is {}", n),
        Err(e) => println!("Error: {}", e),
    }
}

fn main() {
    print(multiply("10", "2"));
    print(multiply("t", "2"));
}
